# Generated by Django 4.1.1 on 2022-12-08 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSignup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=100)),
                ('lname', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=50)),
                ('contect', models.CharField(max_length=12)),
                ('gender', models.CharField(max_length=12)),
                ('image', models.FileField(null=True, upload_to='')),
            ],
        ),
    ]
